services:
  mysql:
    image: mysql:8.0
    container_name: bookstore-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bookstore
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
